image: openjdk:8
pipelines:
  default:
    - step:
        name: Build, Test and Deploy
        caches:
          - maven
        script:
          - chmod +x ./mvnw 
          - ./mvnw -U -B -s settings.xml clean deploy

